import { GoogleGenAI, Modality, Type } from "@google/genai";
import { fileToBase64 } from "../utils/fileUtils";

// Assume process.env.API_KEY is configured in the build environment
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

async function generateSingleImage(baseFile: File, prompt: string): Promise<string> {
    const base64Data = await fileToBase64(baseFile);
    const mimeType = baseFile.type;

    if (!mimeType.startsWith("image/")) {
        throw new Error("Invalid file type. Please upload an image.");
    }

    const finalPrompt = `Faithfully preserve the person's facial features, hairstyle, and hair color from the original image. ${prompt}`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Data,
                        mimeType: mimeType,
                    },
                },
                {
                    text: finalPrompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }
    
    throw new Error("No image was generated by the API.");
}

export async function generateImages(baseFile: File, prompts: string[]): Promise<string[]> {
    const imagePromises = prompts.map(prompt => generateSingleImage(baseFile, prompt));
    return Promise.all(imagePromises);
}

export async function generatePrompts(): Promise<string[]> {
    const metaPrompt = `Generate 5 highly creative and diverse prompts for an AI image generation task. The goal is to place a person from a photo into a new, imaginative scenario. Each prompt should be a single, descriptive sentence specifying a setting, clothing, and style.

    Crucially, it is vital that the person's facial features, hairstyle, and hair color are preserved with high fidelity. The prompt should instruct the AI to maintain these characteristics from the original photo.

    Here are some examples of the desired quality and diversity, which emphasize preserving the person's likeness:
    - "A detailed portrait of this person as a stoic Roman emperor, draped in a regal toga, addressing a crowd in the Colosseum, ensuring their face and hair are accurately represented."
    - "Reimagine this person as a solo astronaut, floating weightlessly inside a spaceship with Earth visible through the window, perfectly preserving their hairstyle even in zero gravity."
    - "Picture this person as a bohemian artist in a sun-drenched Parisian attic studio, splattered with paint, working on a masterpiece. Their facial features and hair color should remain unchanged."
    - "This person as a swashbuckling pirate captain on the deck of their ship, navigating a stormy sea, with their distinct hair and facial structure clearly visible."
    - "Depict this person as a magical librarian in a vast, ancient library, surrounded by floating books and glowing runes, while meticulously maintaining their original appearance."

    Return ONLY a JSON array containing 5 unique prompt strings.`;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: metaPrompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.STRING,
                        description: "A creative prompt for image generation."
                    }
                },
            },
        });

        const prompts = JSON.parse(response.text);
        if (Array.isArray(prompts) && prompts.length > 0) {
            return prompts;
        }
        throw new Error("Received invalid prompt format from API.");
    } catch (e) {
        console.error("Failed to generate or parse prompts:", e);
        // Fallback in case of failure to ensure app functionality
        return [
            "Place this person in a futuristic cityscape, wearing sleek, silver cyberpunk attire, keeping their face and hair the same.",
            "Reimagine this person as a fantasy adventurer, wearing leather armor and standing in an enchanted forest, preserving their original appearance.",
            "Give this person a 1920s vintage makeover, with elegant clothing and a classic black and white film noir background, but don't change their face or hair.",
            "Transform the scene to a vibrant, colorful carnival. The person is wearing festive clothing and is surrounded by confetti, with their original features intact.",
            "Depict this person as a scientist in a high-tech laboratory, wearing a white lab coat and holding a glowing beaker, ensuring their likeness is preserved."
        ];
    }
}